#!/usr/bin/env python3
"""
Train YOLOv8 on GTSRB traffic sign dataset.

Prerequisites:
1. Install ultralytics: pip install ultralytics
2. Download GTSRB dataset from Kaggle or run convert_gtsrb_to_yolo.py

Usage:
    python train_yolov8.py
"""

import os
import sys
from pathlib import Path

def check_dependencies():
    """Check if required packages are installed."""
    try:
        from ultralytics import YOLO
        return True
    except ImportError:
        print("ERROR: ultralytics not installed!")
        print("Run: pip install ultralytics")
        return False


def create_dataset_yaml(data_dir: Path, output_path: Path, class_names: list):
    """Create YOLO dataset configuration file."""
    yaml_content = f"""# SteerMate Traffic Sign Dataset
# Auto-generated by train_yolov8.py

path: {data_dir.absolute()}
train: images/train
val: images/val
test: images/test

# Classes (GTSRB speed limit signs)
names:
"""
    for i, name in enumerate(class_names):
        yaml_content += f"  {i}: {name}\n"
    
    output_path.write_text(yaml_content)
    print(f"Created dataset config: {output_path}")


def main():
    """Train YOLOv8 on traffic signs."""
    print("=" * 60)
    print("SteerMate - YOLOv8 Traffic Sign Training")
    print("=" * 60)
    print()
    
    if not check_dependencies():
        return 1
    
    from ultralytics import YOLO
    
    # Paths
    SCRIPT_DIR = Path(__file__).parent
    TRAINING_DIR = SCRIPT_DIR.parent
    DATA_DIR = TRAINING_DIR / "data"
    MODELS_DIR = TRAINING_DIR / "models"
    BACKEND_ML_DIR = TRAINING_DIR.parent / "ml" / "models"
    
    # Check for dataset
    dataset_yaml = DATA_DIR / "traffic_signs.yaml"
    
    if not dataset_yaml.exists():
        print("WARNING: Dataset not found!")
        print()
        print("You need to prepare the GTSRB dataset first.")
        print("Options:")
        print("  1. Download from Kaggle: https://www.kaggle.com/datasets/meowmeowmeowmeowmeow/gtsrb-german-traffic-sign")
        print("  2. Run: python convert_gtsrb_to_yolo.py")
        print()
        print("For a quick demo, we'll use COCO-pretrained YOLOv8n.")
        print()
        
        # Use base model for demo
        model = YOLO("yolov8n.pt")
        print("Loaded YOLOv8n (COCO pre-trained)")
        print("This model can detect general objects but not specifically traffic signs.")
        print()
        print("Saving base model to ml/models/...")
        
        # Save to ML models directory
        BACKEND_ML_DIR.mkdir(parents=True, exist_ok=True)
        
        # Export to TFLite
        print("\nExporting to TFLite format...")
        model.export(format="tflite")
        
        # Move TFLite file
        tflite_src = Path("yolov8n_saved_model/yolov8n_float32.tflite")
        tflite_dst = BACKEND_ML_DIR / "traffic_signs.tflite"
        
        if tflite_src.exists():
            import shutil
            shutil.copy(tflite_src, tflite_dst)
            print(f"Saved TFLite model to: {tflite_dst}")
        else:
            print("TFLite export may have a different path. Check current directory.")
        
        return 0
    
    # Load YOLOv8 nano model (smallest, fastest)
    print("Loading YOLOv8n model...")
    model = YOLO("yolov8n.pt")
    
    # Configure training
    training_config = {
        "data": str(dataset_yaml),
        "epochs": 50,
        "imgsz": 640,
        "batch": 16,
        "name": "traffic_signs",
        "project": str(MODELS_DIR),
        "patience": 10,  # Early stopping
        "device": "0" if os.system("nvidia-smi > /dev/null 2>&1") == 0 else "cpu",
    }
    
    print(f"Training config: {training_config}")
    print()
    
    # Train
    print("Starting training...")
    results = model.train(**training_config)
    
    # Export best model to TFLite
    print("\nExporting best model to TFLite...")
    best_model_path = MODELS_DIR / "traffic_signs" / "weights" / "best.pt"
    
    if best_model_path.exists():
        best_model = YOLO(best_model_path)
        best_model.export(format="tflite", int8=True)  # Quantized for mobile
        
        # Copy to ml/models
        import shutil
        tflite_files = list(Path(".").glob("**/*_int8.tflite"))
        if tflite_files:
            BACKEND_ML_DIR.mkdir(parents=True, exist_ok=True)
            shutil.copy(tflite_files[0], BACKEND_ML_DIR / "traffic_signs.tflite")
            print(f"Saved TFLite model to: {BACKEND_ML_DIR / 'traffic_signs.tflite'}")
    
    print()
    print("Training complete!")
    print(f"Best model: {best_model_path}")
    
    return 0


if __name__ == "__main__":
    sys.exit(main())
